package org.houseflys.jdbc.parser.lexer;

public enum TokenType {
    EndOfStream,
    Whitespace,
    BareWord,
    StringLiteral,
    QuotedIdentifier,
    OpeningRoundBracket,
    ClosingRoundBracket,
    OpeningSquareBracket,
    ClosingSquareBracket,
    Comma,
    Semicolon,
    ErrorWrongNumber,
    Number,
    Plus,
    Minus,
    Arrow,
    Asterisk,
    Comment,
    ErrorMultilineCommentIsNotClosed,
    Slash,
    Percent,
    Equals,
    ErrorSingleExclamationMark,
    LessOrEquals,
    NotEquals,
    Less,
    GreaterOrEquals,
    Greater,
    QuestionMark,
    Colon,
    Concatenation,
    ErrorSinglePipeMark,
    Error,
    Dot;
}
